CREATE TABLE IF NOT EXISTS laravel_devs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    github_username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    sent TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
